# Generated by Django 2.2.3 on 2019-10-16 21:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_auto_20191016_1806'),
    ]

    operations = [
        migrations.RenameField(
            model_name='curtida',
            old_name='cliente',
            new_name='user',
        ),
        migrations.RenameField(
            model_name='descurtida',
            old_name='cliente',
            new_name='user',
        ),
    ]
