# Generated by Django 2.2.3 on 2019-10-17 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0005_auto_20191016_1822'),
    ]

    operations = [
        migrations.AddField(
            model_name='produto',
            name='curtidas',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='produto',
            name='descurtidas',
            field=models.IntegerField(default=0),
        ),
    ]
