# Generated by Django 2.2.3 on 2019-10-25 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_auto_20191025_1425'),
    ]

    operations = [
        migrations.CreateModel(
            name='Promocao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=21)),
                ('panfleto', models.FileField(blank=True, upload_to='%Y/%m/%d/')),
            ],
        ),
    ]
