# Generated by Django 2.2.3 on 2019-10-25 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_promocao'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'ordering': ['titulo']},
        ),
        migrations.AlterModelOptions(
            name='cliente',
            options={'ordering': ['user']},
        ),
        migrations.AlterModelOptions(
            name='produto',
            options={'ordering': ['nome']},
        ),
        migrations.AlterField(
            model_name='cliente',
            name='sexo',
            field=models.IntegerField(choices=[('Masculino', 'Masculino'), ('Feminino', 'Feminino')]),
        ),
    ]
